"""Starting tables for sprint 1

Revision ID: 28e4b0520a53
Revises: 
Create Date: 2020-10-18 04:27:52.315835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e4b0520a53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_stock_symbol'), 'stock', ['symbol'], unique=False)
    op.create_table('user',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('timeseries',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('open_p', sa.Float(), nullable=True),
    sa.Column('close_p', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('datetime')
    )
    op.create_index(op.f('ix_timeseries_datetime'), 'timeseries', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeseries_datetime'), table_name='timeseries')
    op.drop_table('timeseries')
    op.drop_table('user')
    op.drop_index(op.f('ix_stock_symbol'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
