"""Add volume column

Revision ID: 5f4d41d8bca3
Revises: aef44b7fab9f
Create Date: 2020-10-21 18:15:35.196048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4d41d8bca3'
down_revision = 'aef44b7fab9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseries', sa.Column('volume', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeseries', 'volume')
    # ### end Alembic commands ###
