"""added achievements

Revision ID: 81632812e3b2
Revises: aef44b7fab9f
Create Date: 2020-10-21 19:45:17.821774

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "81632812e3b2"
down_revision = "aef44b7fab9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unlockedachievement",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("achievement_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.uid"],
        ),
        sa.PrimaryKeyConstraint("user_id", "achievement_id"),
    )
    op.create_index(op.f("ix_unlockedachievement_user_id"), "unlockedachievement", ["user_id"], unique=False)
    op.add_column("timeseries", sa.Column("volume", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_unlockedachievement_user_id"), table_name="unlockedachievement")
    op.drop_table("unlockedachievement")
    op.drop_column("timeseries", "volume")
    # ### end Alembic commands ###
