"""tables v3: sprint 1 tables

Revision ID: 9fb3855ec5ff
Revises: c2d49154ffb9
Create Date: 2020-10-16 02:18:13.065074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb3855ec5ff'
down_revision = 'c2d49154ffb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_stock_symbol'), 'stock', ['symbol'], unique=False)
    op.create_table('user',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('stockdata',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('stock_symbol', sa.String(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('open_p', sa.Float(), nullable=True),
    sa.Column('close_p', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_symbol'], ['stock.symbol'], ),
    sa.PrimaryKeyConstraint('datetime')
    )
    op.create_index(op.f('ix_stockdata_datetime'), 'stockdata', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stockdata_datetime'), table_name='stockdata')
    op.drop_table('stockdata')
    op.drop_table('user')
    op.drop_index(op.f('ix_stock_symbol'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
