"""primitive version of watchlist and portfolio

Revision ID: aef44b7fab9f
Revises: 2674935da709
Create Date: 2020-10-20 04:36:37.945113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef44b7fab9f'
down_revision = '2674935da709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('avg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('user_id', 'symbol')
    )
    op.create_table('watchlist',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('user_id', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
