"""Add short selling

Revision ID: c0865da9899b
Revises: 81632812e3b2
Create Date: 2020-10-22 15:39:18.538432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0865da9899b'
down_revision = '81632812e3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortsell',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('avg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stock.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('user_id', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortsell')
    # ### end Alembic commands ###
