"""tables v2: update table

Revision ID: c2d49154ffb9
Revises: c5eaf5b1610e
Create Date: 2020-10-16 01:12:21.817429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2d49154ffb9"
down_revision = "c5eaf5b1610e"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("user")
    op.drop_table("stock")
    op.drop_table("stockdata")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("exchange", sa.String(), nullable=True),
        sa.Column("exchange_timezone", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_index(op.f("ix_stock_symbol"), "stock", ["symbol"], unique=False)
    op.create_table(
        "user",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("token", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    op.create_table(
        "stockdata",
        sa.Column("id", sa.DateTime(), nullable=False),
        sa.Column("stock_symbol", sa.String(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("open_p", sa.Float(), nullable=True),
        sa.Column("close_p", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["stock_symbol"],
            ["stock.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stockdata_id"), "stockdata", ["id"], unique=False)
