run: 
	bash start.sh run

initial-populate: 
	bash start.sh initial-populate ${env} ${firebase}

check-wake:
	bash start.sh check-wake

init-db:
	bash start.sh init-db

nuke-db-from-orbit:
	bash start.sh nuke-db-from-orbit

setup-test:
	bash start.sh setup-test

setup-pythonpath:
	bash start.sh setup-pythonpath

run-test:
	bash start.sh run-test